
INSERT INTO districts (id, name, province_id) VALUES (default, 'Ancuabe', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Balama', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chiúre', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Ibo', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Macomia', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mecúfi', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Meluco', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Metuge', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mocímboa da Praia', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Montepuez', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mueda', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muidumbe', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Namuno', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nangade', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Palma', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Pemba', 11);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Quissanga', 11);

INSERT INTO districts (id, name, province_id) VALUES (default, 'Bilene', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chibuto', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chicualacuala', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chigubo', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chókwè', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chongoene', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Guijá', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Limpopo', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mabalane', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Manjacaze', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mapai', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muidumbe', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Massangena', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Massingir', 8);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Xai-Xai', 8);

INSERT INTO districts (id, name, province_id) VALUES (default, 'Funhalouro', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Govuro', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Homoíne', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Inhambane', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Inharrime', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Inhassoro', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Jangamo', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mabote', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Massinga', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Maxixe', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Morrumbene', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muidumbe', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Panda', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Vilanculos', 7);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Zavala', 7); 
      
INSERT INTO districts (id, name, province_id) VALUES (default, 'Bárue', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chimoio', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Gondola', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Guro', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Macate', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Machaze', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Macossa', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Manica', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mossurize', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Sussundenga', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Tambara', 5);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Vanduzi', 5);
      
INSERT INTO districts (id, name, province_id) VALUES (default, 'Boane', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Magude', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Manhiça', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Marracuene', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Matola', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Matutuíne', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Moamba', 9);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Namaacha', 9); 
      
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaMpfumo', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nlhamankulu', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaMaxaquene', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaMavota', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaMubukwana', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaTembe', 10);
INSERT INTO districts (id, name, province_id) VALUES (default, 'KaNyaka', 10); 
      
INSERT INTO districts (id, name, province_id) VALUES (default, 'Angoche', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Eráti', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Ilha de Moçambique', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Lalaua', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Larde', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Liúpo', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Malema', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Meconta', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mecubúri', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Memba', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mogincual', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mogovolas', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Moma', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Monapo', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mossuril', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muecate', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Murrupula', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nacala-a-Velha', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nacala Porto', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nacarôa', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nampula', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Rapale', 2);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Ribáuè', 2);
      
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chimbonila', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Cuamba', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Lago', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Majune', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mandimba', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Marrupa', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Maúa', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mavago', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mecanhelas', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mecula', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Metarica', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muembe', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'N''gauma', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nipepe', 1);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Sanga', 1);

INSERT INTO districts (id, name, province_id) VALUES (default, 'Beira', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Búzi', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Caia', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chemba', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Cheringoma', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chibabava', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Dondo', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Gorongosa', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Machanga', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Maringué', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Marromeu', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Muanza', 6);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nhamatanda', 6);

INSERT INTO districts (id, name, province_id) VALUES (default, 'Angónia', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Cahora-Bassa', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Changara', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chifunde', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chiuta', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Dôa', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Macanga', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Magoé', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Marara', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Marávia', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Moatize', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mutarara', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Tete', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Tsangano', 4);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Zumbo', 4); 

INSERT INTO districts (id, name, province_id) VALUES (default, 'Alto Molócuè', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Chinde', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Derre', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Gilé', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Gurué', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Ile', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Luabo', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Lugela', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Maganja da Costa', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Milange', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mocuba', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mocubela', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Molumbo', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mopeia', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Morrumbala', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Mulevala', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Namacurra', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Namarroi', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Nicoadala', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Pebane', 3);
INSERT INTO districts (id, name, province_id) VALUES (default, 'Quelimane', 3);

                     